### ISSUE TITLE
server should respect .chcpignore

### ISSUE THREAD

**Issue by ptarjan** [nordnet/cordova-hot-code-push-cli#10]
when running `cordova-hcp` I get tons of spurious updates for my vim swap files even though I have them in my
`.chcpignore`

```
$ cat .chcpignore
chcp.json
chcp.manifest
.*.sw[a-p]
.DS_Store
$ cordova-hcp server
Running server
Checking:  www
local_url http://localhost:31284
Config { release: '2015.10.14-13.32.30' }
Build 2015.10.14-13.32.30 created in www
cordova-hcp local server available at: http://localhost:31284
cordova-hcp public server available at: https://291b3fb6.ngrok.com
a user connected
File changed:  www/js/index/.index.js.swp
Config { release: '2015.10.14-13.32.51' }
Build 2015.10.14-13.32.51 created in www
Should trigger reload for build: 2015.10.14-13.32.51
File changed:  www/js/index/index.js
Config { release: '2015.10.14-13.32.56' }
Build 2015.10.14-13.32.56 created in www
Should trigger reload for build: 2015.10.14-13.32.56
File changed:  www/js/index/.index.js.swp
Config { release: '2015.10.14-13.33.01' }
Build 2015.10.14-13.33.01 created in www
Should trigger reload for build: 2015.10.14-13.33.01
```

**Comment by ptarjan** [comment]
It looks like you wanted to but forgot about it: https://github.com/nordnet/cordova-hot-code-push-cli/blob/master/src/server.js#L4

**Comment by nikDemyankov** [comment]
If you open `https://291b3fb6.ngrok.com/chcp.manifest` - those `.sw[a-p]` files are there? If you have changed `.chcpignore` first, and only then ran the server, then they shouldn't. Server detects, that something has changed, shows message about it. But plugin detects, that there is nothing new and no update is performed. So, files from the `.chcpignore` are ignored by the server, but, probably, CLI should not show that confusing messages.

**Comment by ptarjan** [comment]
No, the `manifest` is clean of all my ignores, that works. It is just the server that tries to ping the app constantly for updates for ignored files.

For example, I edit `index.js`, the app gets pinged once for the `.index.js.swp`, then once for the `index.js`, then again after browserify has run and built a `all.js`. So 3 pings go to the app. It probably ignores 2 of them an only reacts to the `all.js` but I'm worried the messages might get out of order, or two might co-incide, or something bad could happen. I'd rather it just get pinged once for my `all.js` since that is the only thing in the `www` dir I didn't want ignored.

**Comment by nikolasleblanc** [comment]
Sorry to comment on a closed issue, but I just have a question about chpignore, not a bug or anything, so best to hide it here. Can I exclude files from being copied to local storage with the chpignore, so that the app knows to get update-able files from server/localstorage but can load all other "deemed-non-changing" files from the app itself, or is it just used to update the manifest about what files have changed - as opposed to what files should be sent to the server? Just curious.

**Comment by nikDemyankov** [comment]
`.chcpignore` is used by the CLI client to form manifest file. And nothing more. Plugin itself doesn't know about it's existents.

We can't break content of the `www` folder on copyable and not-copyable files, because if files are in `www` folder - then they are used on the web pages. And if so - you need to know path to them (for example, for css files). Usually, those paths are relative. But if you break content on different parts - you need to provide absolute paths to them, which, I'm not sure, even possible. Either way, this will lead to a serious complication of the logic on the web project itself.
