### ISSUE TITLE
document env.version

### ISSUE THREAD

**Issue by pablomaurer** [nordnet/cordova-hot-code-push-cli#65]
So first time looked into the code and found out instead having the generated release timestamp you can run:
```
VERSION=3 cordova-hcp build
```
to set your own version. 

If you are cool, then let people know you are ;)

**Comment by nikDemyankov** [comment]
I've been rewriting CLI client to support new configs. And eventually was planning to add arguments to the command like you pointed out. But instead of environment variables they should be a regular CLI arguments. For instance:

``` bash
cordova-hcp build --version='123123'
```

I can add this to docs, but this environment variable might be deprecated soon, so not sure that should be in there :)

**Comment by pablomaurer** [comment]
Yep, then a issue where you can find it should be enough until `--version` arrives ;)
